### ISSUE TITLE
pubsub editor attributes header missing

### ISSUE THREAD

**Issue by josemiguellopez** [rollno748/Jmeter-pubsub-sampler#2]
attached image

![image](https://user-images.githubusercontent.com/42448510/108841381-6988c200-75b6-11eb-8919-a1b0b11c71c6.png)

**Comment by rollno748** [comment]
Hello Jose,

The code was merged to Github. but, didn't released it as upgraded version.
We have some other changes as well. Will publish it this weekend.

For time being, you can download the code from the master and build it using maven- That should help you to get the issue resolved 

Thanks,

**Comment by rollno748** [comment]
The new version is out in jmeter plugins.
You should be able to download using plugins manager.

The released version 1.1 should resolve this issue

**Comment by josemiguellopez** [comment]
thanks works perfect
