### ISSUE TITLE
Adding publisher config

### ISSUE THREAD

**Issue by timoleinio** [rollno748/Jmeter-pubsub-sampler#5]
Hello!

When I try to add config for a publisher Add > Config element > PubSub-PublisherConfiguration nothing happens. How should the config be given? Should a section open in the right side of jMeter as  it does while adding other configs?

Using jMeter 5.4.1

**Comment by rollno748** [comment]
Hello,

You tried the right path (Test plan -> rightclick -> Add-> config element-> PubSub-PublisherConfig)  
It should add an element to the test plan.

Did you notice any errors in Jmeter.log File ?

Can you share your jmeter.log file please ?
Also, can you verify that the Plugin jar is available inside 'JmeterDir/lib/ext' ?

**Comment by timoleinio** [comment]
Yeah, my bad. I didn't have google-cloud-pubsub-1.111.2.jar, gson-2.2.4.jar under ext folder. Works ok now

**Comment by rollno748** [comment]
Okay 
I dont think you need the google-cloud-pubsub jar - because , i have created it as a fat jar - it should be within the plugin 

Anyways, If you like it - please don't forgot to hit the star on the github repo

Enjoy Testing !!
